services:
  backend:
    build:
      context: ./back-clareia
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./front-clareia
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:8000/api
